[ADD] Architecture for part 2

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -18,12 +18,22 @@ jobs:
         run: make
       - name: Check Binary
         run: |
-          if [ ! -f "./${{ inputs.executable_name }}" ]; then exit 1; fi
+          for exe in ${{ inputs.executable_name }}; do
+            if [ ! -f "./$exe" ]; then
+              echo "Binary $exe not found"
+              exit 1
+            fi
+          done
       - name: Check Clean
         run: |
           make clean
           make fclean
-          if [ -f "./${{ inputs.executable_name }}" ]; then exit 1; fi
+          for exe in ${{ inputs.executable_name }}; do
+            if [ -f "./$exe" ]; then
+              echo "Binary $exe still exists after fclean"
+              exit 1
+            fi
+          done
 
   run_tests:
     needs: build_and_check
