[MERGE] Dev
* [ADD] all file from epitech repository

* [ADD] commint lint file to prevent bad commit message

* [ADD] script to init github hooks and add functionnal test

* [ADD] docusaurus implementation on repo

* [ADD] docusaurus package

* [ADD] pull request template and Code owners file

* [CI] add module to execute automated task

* [CI] add orchestrator file for github action

* [CI] fix architecture of ci by deleting dir modules

* [CI] fix architecture of ci by deleting dir modules

* [CI] fix commit lint to add MERGE type

* [CI] fix container in build and test task

* [CI] fix stack error that write on the root folder in docker

* [CI] fix stack error with user mismatch

* [CI] fix stack error with user mismatch

* [CI] fix stack error with user mismatch

* [CI] fix fetch-depth on lint action

* [CI] fix Validate pr commit task

* [CI] fix Generate Haddock task in documentation action

* [CI] rebase main into dev

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -4,27 +4,39 @@ on: workflow_call
 jobs:
   deploy_docs:
     runs-on: ubuntu-latest
-    permissions: { contents: write }
+    permissions:
+      contents: write
     steps:
       - uses: actions/checkout@v4
-      - uses: haskell-actions/setup@v2
-        with: { enable-stack: true }
-      
-      # 1. Generate Haddock
-      - run: stack haddock --no-haddock-deps
-      - run: |
-          mkdir -p documentation/static/api
-          cp -r $(stack path --local-doc-root)/* documentation/static/api/
 
-      # 2. Build Docusaurus
+      - uses: haskell-actions/setup@v2
+        with:
+          enable-stack: true
+      
+      - name: Build Haddock
+        run: stack haddock --no-haddock-deps
+
+      - name: Move API Docs to Docusaurus
+        run: |
+          DOC_PATH=$(stack path --local-doc-root)
+          echo "Documentation found at: $DOC_PATH"
+          
+          ls -la "$DOC_PATH" || echo "Folder not found!"
+
+          mkdir -p documentation/static/api
+
+          cp -r "$DOC_PATH"/. documentation/static/api/
+
       - uses: actions/setup-node@v3
+        with:
+          node-version: 'latest'
+
       - name: Build Site
         working-directory: ./documentation
         run: |
           npm ci
           npm run build
 
-      # 3. Deploy
       - uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
